fix(a): b
c

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -32,8 +32,14 @@ jobs:
         run: |
           tag_name=$(echo ${GITHUB_REF#refs/tags/})
           issue=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{github.token}}" https://api.github.com/repos/${{github.repository}}/issues \
-          -d '{"title":"Artifact Promotion for \${tag_name}","body":"# New promotion pipeline created for tag **${tag_name}** \n | Environment | Promoted | \n |---|---| \n | Staging |✅| \n | Demo  |🔲| \n | Sandbox  |🔲| \n | Production  |🔲|","assignees":["fergo2910"],"labels":["promotion-pipeline"]}')
+          -d "{\"title\":\"Artifact Promotion for \${tag_name}\",\"body\":\"# New promotion pipeline created for tag **\${tag_name}** \n | Environment | Promoted | \n |---|---| \n | Staging |✅| \n | Demo  |🔲| \n | Sandbox  |🔲| \n | Production  |🔲|\",\"assignees\":[\"fergo2910\"],\"labels\":[\"promotion-pipeline\"]}")
           issue_number=$(echo ${issue} | jq '.number')
-          echo "Issue ID created"
-          echo "https://github.com/${{github.repository}}/issues/${issue_number}"
-          echo "url=https://github.com/${{github.repository}}/issues/${issue_number}" >> $GITHUB_OUTPUT
+          if [[ $issue_number != "null" ]];
+          then
+            echo "Issue ID created"
+            echo "https://github.com/${{github.repository}}/issues/${issue_number}"
+            echo "url=https://github.com/${{github.repository}}/issues/${issue_number}" >> $GITHUB_OUTPUT
+          else
+            echo "Error creating the issue"
+            exit 1
+          fi
